# example netlify.toml
[build]
  # The directory where the production build files are stored
  publish = "dist"
  
  # The command to build the site
  command = "vite build"

  # Specify the default branch for production builds (usually 'main' or 'master')
  branch = "main"

[[plugins]]
  # Optional: Vite plugin to improve build performance on Netlify
  package = "@netlify/plugin-vite"

[context.production.environment]
  # Production-specific environment variables
  VITE_APP_ENV = "production"
  BASE_URL = "https://gidiazsolutions.netlify.app/"  # URL of the deployed site

[context.branch-deploy.environment]
  # Optionally define branch-specific environment variables for branch deploys
  VITE_APP_ENV = "staging"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
